version: '3.8'

services:
  app:
    build: .
    container_name: conclusion-nexus-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 