version: '3.8'

services:
  backend:
    build: ./backend
    container_name: conclusion-nexus-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "3101:3003"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: conclusion-nexus-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:3101
    ports:
      - "3100:3000"
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: conclusion-nexus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3102:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_DATABASE_TYPE=postgresdb
      - N8N_DATABASE_POSTGRESDB_HOST=postgres
      - N8N_DATABASE_POSTGRESDB_PORT=5432
      - N8N_DATABASE_POSTGRESDB_DATABASE=n8n
      - N8N_DATABASE_POSTGRESDB_USER=n8n
      - N8N_DATABASE_POSTGRESDB_PASSWORD=n8n_passwordinhdfd80y32423hnbdfNdsifsp
      - N8N_DATABASE_POSTGRESDB_SCHEMA=public
      - N8N_DATABASE_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_PORT=5678
      - N8N_EXPRESS_TRUST_PROXY=true
    ports:
      - "3103:5678"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: 